### ISSUE TITLE
Tested with a "real" alarm

### ISSUE THREAD

**Issue by jradwan** [realSixi/node-red-contrib-ring-alarm#1]
Not an issue, just wanted to let you know I did test this with an actual alarm event. Using the msg.payload.state = "burglar-alarm" from the Alarm Status node worked perfectly. 

I was using Alexa Routines before this, but the only alarm states that Alexa can see are Armed Home, Armed Away, and Disarmed ... there's no Alarming state:

https://community.ring.com/t/alexa-routine-trigger-for-when-alarm-is-going-off/36215

Now with Node-Red and your package I can trigger HomeSeer events when the Ring alarm is going off ... thank you!

**Comment by realSixi** [comment]
Hej jradwan, 

thank you for your feedback, great to hear it's working with real alarms!

**Comment by jradwan** [comment]
Closing since this was just a comment. :)
