### ISSUE TITLE
Expiring refresh token?

### ISSUE THREAD

**Issue by jradwan** [realSixi/node-red-contrib-ring-alarm#2]
My Node-Red flows for Ring stopped working overnight. It looks like my refresh token expired.

I run Homebridge on the same server and noticed it had stopped connecting to Ring as well due to an expired token. I've been using Homebridge and Ring for a while without an issue. According to the refresh token wiki (https://github.com/dgreif/ring/wiki/Refresh-Tokens) it handles updating the config with a new token when issued.

Does the same thing happen with for these Ring nodes in Node-Red? I've got everything working again (generated a new refresh token in the Ring Homebridge plug-in, then pasted it quickly into my Node-Red config), but wondering if it will expire again? I'll keep an eye on it, just wondering.

Thanks.

**Comment by realSixi** [comment]
Cant replicate this issue. I have two setups and both work reliable since release.

**Comment by jradwan** [comment]
I actually forgot I had logged this and haven't run into the issue again either. Thank you!
