### ISSUE TITLE
FR: add support for LocationMode

### ISSUE THREAD

**Issue by peda** [realSixi/node-red-contrib-ring-alarm#3]
Alarm Mode is only supported if you do have any Ring alarm devices, but if someone is only using Ring cameras and doesn't have a ring alarm system, then setting the alarm mode will fail with the error message `Could not find a security panel for location` (see https://github.com/dgreif/ring/issues/533)

In this case `setLocationMode` should be used instead - as the API for `setAlarmMode` is very similar, it should be a rather simple task to add support for `setLocationMode`

**Comment by realSixi** [comment]
Hi @peda 
Thanks for your feedback. I just releases a new version that uses setLocationMode as a fallback. Due i have no setup with only cameras, can you test if it works? :)

Thanks in advance!
