### ISSUE TITLE
Any chance this could support node v14 too?

### ISSUE THREAD

**Issue by bcrosser** [realSixi/node-red-contrib-ring-alarm#8]
I'm working with older versions of node and find this interesting and would be interested in the work entailed in supporting an older version of node.

**Comment by realSixi** [comment]
Hey,
as the used library [ring-api-client](https://github.com/dgreif/ring/tree/main/packages/ring-client-api) requires node >=16, I don't think it would be possible to run this plugin with node 14, sorry.
